[package]
name = "bevy_mod_index"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.9.1", default_features = false }

# Dependencies for examples
[dev-dependencies]
bevy = { version = "0.9.1", features = ["dynamic"] }
rand = "0.8.5"
